version: '3'
services:
    markov-toot:
        restart: always
        container_name: markov-toot
        image: ghcr.io/yuderobot/markov-toot:master
        build: .
        volumes:
          - "./data:/app/data"
        environment:
          - DOMAIN=
          - TOKEN=